@token = {{login.response.body.token}}

### Add user
POST http://localhost:5000/registration
Content-type: application/json

{
    "name": "Julie",
    "email": "test@gmail.com",
    "password": "123465678"
}

### Login
# @name login
POST http://localhost:5000/login
Content-type: application/json

{
    "email": "test@gmail.com",
    "password": "123465678"
}

### Get all tasks
GET  http://localhost:5000/tasks
Authorization: Bearer {{token}}

### Add task
POST  http://localhost:5000/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Buy milk"
}

### Get task by Id
GET http://localhost:5000/tasks/6a71f28d3bee35c80c0470a8
Authorization: Bearer {{token}}


### Change task
PUT http://localhost:5000/tasks/6a71f28d3bee35c80c0470a8
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Buy bio milk"
}

### Toggle complete
PATCH http://localhost:5000/tasks/6a71f28d3bee35c80c0470a8
Authorization: Bearer {{token}}

### Delete task
DELETE http://localhost:5000/tasks/6a71f28d3bee35c80c0470a8
Authorization: Bearer {{token}}

### Test Sentry
GET http://localhost:5000/test-sentry

### Check without token
GET http://localhost:5000/readFile
